# Generated by Django 4.1.5 on 2023-02-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('forename', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('join_date', models.DateTimeField(verbose_name='date joined')),
                ('skillset', models.ManyToManyField(to='users.skill')),
            ],
        ),
    ]
