# Generated by Django 4.1.5 on 2023-02-12 16:46

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='01202-764514', max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
    ]
