# Generated by Django 4.1.5 on 2023-02-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='zbenattar@warwick.ac.uk', max_length=254),
            preserve_default=False,
        ),
    ]
