# Generated by Django 4.1.5 on 2023-03-03 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 18, 45, 39, 771698, tzinfo=datetime.timezone.utc)),
        ),
    ]
