# Generated by Django 4.1.5 on 2023-03-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='members',
            field=models.ManyToManyField(blank=True, to='projects.member'),
        ),
    ]
