# Generated by Django 4.1.5 on 2023-02-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_rolerequirements_rolerequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeworked',
            name='time',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
