# Generated by Django 4.1.5 on 2023-03-07 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_member_salary_project_amount_spent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='user_profile',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 16, 59, 35, 127249, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 16, 59, 35, 111614, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='initial_deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 16, 59, 35, 111614, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 7, 16, 59, 35, 111614, tzinfo=datetime.timezone.utc)),
        ),
    ]
