# Generated by Django 4.1.5 on 2023-02-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_meeting_createdtime_member_joinedtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
