# Generated by Django 4.1.5 on 2023-02-16 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_paused'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='joinedTime',
            new_name='joinedDate',
        ),
        migrations.AddField(
            model_name='project',
            name='startTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='startedTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
