# Generated by Django 4.1.5 on 2023-02-16 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_riskevaluation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskevaluation',
            old_name='riskEvaluation',
            new_name='riskScore',
        ),
    ]
