# Generated by Django 4.1.5 on 2023-02-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_riskevaluation_riskevaluation_riskscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
