# Generated by Django 4.1.5 on 2023-02-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='createdTime',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='joinedDate',
            new_name='joined_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='createdTime',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='currentBudget',
            new_name='current_budget',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='currentDeadline',
            new_name='current_deadline',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='gitHubToken',
            new_name='gitHub_token',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='initialBudget',
            new_name='initial_budget',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='initialDeadline',
            new_name='initial_deadline',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='startTime',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='createdTime',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='riskevaluation',
            old_name='riskScore',
            new_name='success_chance',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='createdTime',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='rolerequirement',
            old_name='createdTime',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='createdTime',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='completionStatus',
            new_name='completion_status',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='createdTime',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='startedTime',
            new_name='started_date',
        ),
    ]
