# Generated by Django 4.1.5 on 2023-02-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_rename_createdtime_meeting_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='workhours',
            new_name='work_hours',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='paused',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='role',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='rolerequirement',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='started_date',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
