# Generated by Django 4.1.5 on 2023-03-08 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_riskevaluation_initial_evaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectResult',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 13, 55, 30, 768862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 13, 55, 30, 768862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='initial_deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 13, 55, 30, 768862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 13, 55, 30, 768862, tzinfo=datetime.timezone.utc)),
        ),
    ]
