# Generated by Django 4.1.5 on 2023-03-06 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_member_developer_alter_meeting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 22, 2, 34, 321270, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='current_deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 22, 2, 34, 319269, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='initial_deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 22, 2, 34, 319269, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 6, 22, 2, 34, 319269, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='riskevaluation',
            name='success_chance',
            field=models.DecimalField(decimal_places=10, max_digits=13),
        ),
    ]
