# Generated by Django 4.1.5 on 2023-02-23 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_member_join_date_task_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
