# Generated by Django 4.1.5 on 2023-02-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_recommendation_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='created_date',
            new_name='creation_date',
        ),
    ]
