# Generated by Django 4.1.5 on 2023-02-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_rename_created_date_recommendation_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dependent_tasks',
            field=models.ManyToManyField(related_name='prerequisites', to='projects.task'),
        ),
    ]
