# Generated by Django 4.1.5 on 2023-02-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_task_dependent_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dependent_tasks',
            field=models.ManyToManyField(blank=True, related_name='prerequisites', to='projects.task'),
        ),
    ]
